//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TankControl
{
    public partial class History
    {
        public int id { get; set; }
        public int recipe_id { get; set; }
        public string recipe_name { get; set; }
        public System.DateTime date { get; set; }
        public double el1 { get; set; }
        public double el2 { get; set; }
        public double el3 { get; set; }
        public double el4 { get; set; }
        public double el5 { get; set; }
        public double el6 { get; set; }
        public double el7 { get; set; }
        public double total { get; set; }
        public int duration_el1 { get; set; }
        public int duration_el2 { get; set; }
        public int duration_el3 { get; set; }
        public int duration_el4 { get; set; }
        public int duration_el5 { get; set; }
        public int duration_el6 { get; set; }
        public int duration_el7 { get; set; }

        public History()
        {
            this.date = DateTime.Now;
        }

        public History(int recipeID, string recipeName)
        {
            this.date = DateTime.Now;
            this.recipe_id = recipeID;
            this.recipe_name = recipeName;
        }
        public virtual Recipe Recipe { get; set; }
    }
    
}
