//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TankControl.Class;

namespace TankControl
{
    public partial class Recipe
    {
        public Recipe()
        {
            this.Histories = new HashSet<History>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public double el1 { get; set; }
        public double el2 { get; set; }
        public double el3 { get; set; }
        public double el4 { get; set; }
        public double el5 { get; set; }
        public double el6 { get; set; }
        public double el7 { get; set; }
        public double tol_el1 { get; set; }
        public double tol_el2 { get; set; }
        public double tol_el3 { get; set; }
        public double tol_el4 { get; set; }
        public double tol_el5 { get; set; }
        public double tol_el6 { get; set; }
        public double tol_el7 { get; set; }
        public double switch_el1 { get; set; }
        public double switch_el2 { get; set; }
        public int runtime { get; set; }
    
        public virtual ICollection<History> Histories { get; set; }

        public bool IsValid()
        {
            bool valid = false;

            double sumAll = this.el1 + this.el3 + this.el4 + this.el5 + this.el6 + this.el7;

            if (sumAll <= TankControl.Properties.Settings.Default.Limit)
            {
                valid = true;
            }

            return valid;
        }
    }
    
}
