//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TankControl
{
    public partial class SystemError
    {
        public int id { get; set; }
        public Nullable<int> errorLevel { get; set; }
        public string errorDesc { get; set; }
        public string errorLocation { get; set; }
        public Nullable<System.DateTime> errorDate { get; set; }
        public Nullable<int> errorLevel { get; set; }
    }
    
}
